# -*- coding: utf-8 -*-
"""
/***************************************************************************
 enveloppe_by_field
                                 A QGIS plugin
 create evnloppe of point by field
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-11
        copyright            : (C) 2024 by Gacemi Mohamed el Amine
        email                : gacemiamine@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load enveloppe_by_field class from file enveloppe_by_field.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Envelope_By_Field import enveloppe_by_field
    return enveloppe_by_field(iface)
