# -*- coding: utf-8 -*-
"""
/***************************************************************************
 enveloppe_by_field
                                 A QGIS plugin
 create evnloppe of point by field
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-02-11
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gacemi Mohamed el Amine
        email                : gacemiamine@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import *

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .Envelope_By_Field_dialog import enveloppe_by_fieldDialog
import os.path


class enveloppe_by_field:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.
        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'enveloppe_by_field_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&EnvelopeByField')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('enveloppe_by_field', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/Envelope_By_Field/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Envelope'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True
        


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&EnvelopeByField'),
                action)
            self.iface.removeToolBarIcon(action)

    def selectField(self):
        self.dlg.comboBox2.clear()
        index=self.dlg.comboBox.currentIndex()
        layers = [layer for layer in QgsProject.instance().mapLayers().values()]
        layer=layers[index]
        #vpr=layer.DataProvider()
        fields=layer.fields()
        a=[]
        for f in fields:
            a.append(f.name())
        self.dlg.comboBox2.addItems(a)
    def createEnvelope(self):
        uri = "Polygon?crs=epsg:4326&field=Names:string(25)"
        vPolygon = QgsVectorLayer(uri, "Enveloppe layer",  "memory")
        
        vPolygon.isValid()
        vpr=vPolygon.dataProvider()
        field=vpr.fields()
        layers = [layer for layer in QgsProject.instance().mapLayers().values()]
        index=self.dlg.comboBox.currentIndex()
        layer=layers[index]
        liste_vu=[]
        uniqueprovider=layer.dataProvider()
        fields=uniqueprovider.fields()
        fiels_nom=self.dlg.comboBox2.currentText()
        id=fields.indexFromName(fiels_nom)
        liste_vu=uniqueprovider.uniqueValues(id)
        points=[]
        for uv in liste_vu:
            print("k")
            points[:]=[]
            for feature in layer.getFeatures():
                if uv==feature[fiels_nom]:
                    geom=feature.geometry()
                    points.append(geom.asPoint())
            print([points])
            poly=QgsGeometry.fromPolygonXY([points])
            feature=QgsFeature(fields)
            feature[fiels_nom]=uv
            feature.setGeometry(poly)
            vpr.addFeatures([feature])
        
        QgsProject.instance().addMapLayer(vPolygon)
        print("oooo")
            

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = enveloppe_by_fieldDialog()

        # show the dialog
        self.dlg.show()
        self.dlg.pushButton.clicked.connect(self.createEnvelope)
        self.dlg.comboBox.currentTextChanged.connect(self.selectField)
        # charger les couches dans le combobox
        layers = [layer for layer in QgsProject.instance().mapLayers().values()]
        Liste=[]
        self.dlg.comboBox.clear()
        for layer in layers:
            Liste.append(layer.name())
        self.dlg.comboBox. addItems(Liste)
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
